version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build-and-push:
    working_directory: ~/repo
    executor: docker/docker
    docker:
      - image: cimg/php:8.4
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Build Docker Image"
          command: |
            docker buildx create --use
            docker buildx build --platform linux/amd64 -t docker.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest -f Dockerfile .
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
          registry: docker.io

workflows:
  commit:
    jobs:
      - build-and-push:
          context:
            - docker