version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build-and-push:
    working_directory: ~/repo
    executor: docker/docker
    docker:
      - image: cimg/php:8.4
    steps:
      # - docker/check:
      #     docker-username: DOCKER_USERNAME
      #     docker-password: DOCKER_PASSWORD
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
          dockerfile: Dockerfile
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
          registry: docker.io

workflows:
  commit:
    jobs:
      - build-and-push:
          context:
            - docker