version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build-and-push:
    working_directory: ~/repo
    executor: docker/docker
    docker:
      - image: cimg/php:8.4
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Docker Hub Login"
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
      - run:
          name: "Build docker image"
          command: |
            docker build -t tomasdav9/test-laravel-app:latest .
      
      - docker/push:
          image: tomasdav9/test-laravel-app
          tag: latest
          registry: docker.io

workflows:
  commit:
    jobs:
      - build-and-push:
          context:
            - docker