apiVersion: v1
kind: ConfigMap
metadata:
  name: test-laravel-app-config
  namespace: test-laravel-app
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_URL: "http://localhost"
  APP_DEBUG: "true"
  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"
  APP_MAINTENANCE_DRIVER: "file"
  
  PHP_CLI_SERVER_WORKERS: "4"
  BCRYPT_ROUNDS: "12"
  
  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"
  
  DB_CONNECTION: "mariadb"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  DB_HOST: 'mariadb-service'
  DB_DATABASE: 'laravel'
  DB_PASSWORD: 'password'
  MYSQL_ROOT_PASSWORD: 'password'
  MYSQL_DATABASE: 'laravel'
  
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"
  
  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "database"
  
  CACHE_STORE: "database"