apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: test-laravel-app
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: test-laravel-app
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.6
        name: mariadb
        envFrom:
        - configMapRef:
            name: test-laravel-app-config
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mariadb
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: test-laravel-app
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
  type: ClusterIP