version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build-and-push:
    working_directory: ~/repo
    executor: docker/docker
    docker:
      - image: cimg/php:8.4
    steps:
      - checkout
      - run:
          name: "Change to Laravel Directory"
          command: cd Laravel
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Laravel/composer.json" }}
            - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: composer install -n --prefer-dist --ignore-platform-reqs --working-dir=Laravel
      - save_cache:
          key: v1-dependencies-{{ checksum "Laravel/composer.json" }}
          paths:
            - Laravel/vendor
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
          dockerfile: Laravel/Dockerfile
          path: ./Laravel
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
          registry: docker.io

workflows:
  commit:
    jobs:
      - build-and-push:
          context:
            - docker